name: Rust

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
  
    - name: Create Release Directory
      run: mkdir -p release

    - name: Build
      if: github.event.head_commit.message != 'Update rust.yml' && github.event.head_commit.message != 'Github Bot'
      run: cargo build --verbose --release --bin rustube-api

    - name: Move Build Output (Ubuntu)
      if: matrix.platform == 'ubuntu-latest' &&  github.event.head_commit.message != 'Update rust.yml' && github.event.head_commit.message != 'Github Bot'
      run: cp target/release/rustube-api release/rustube-api-ubuntu
      
    - name: Move Build Output (Windows)
      if: matrix.platform == 'windows-latest'&&  github.event.head_commit.message != 'Update rust.yml' && github.event.head_commit.message != 'Github Bot'
      run: cp target/release/rustube-api.exe release/rustube-api-windows.exe
      
    - name: Upload Artifact
      if:  github.event.head_commit.message != 'Update rust.yml' && github.event.head_commit.message != 'Github Bot'
      uses: actions/upload-artifact@v2
      with:
        name: release-${{ matrix.platform }}
        path: release

    - name: "Commit and push release folder"
      if: github.event.head_commit.message != 'Update rust.yml' && github.event.head_commit.message != 'Github Bot'
      run: |
        git config --global user.name 'Bobby the Bot'
        git config --global user.email 'christophervos522@gmail.com'
        git add release/
        git commit -m "Github Bot"
        git push origin main
