name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: cargo build --verbose --release
      
    - name: Create Release Directory
      run: mkdir release
      
    - name: Move Build Output (Ubuntu)
      if: matrix.platform == 'ubuntu-latest'
      run: mv target/release/${{ github.event.repository.name }} release/${{ github.event.repository.name }}-ubuntu
      
    - name: Move Build Output (Windows)
      if: matrix.platform == 'windows-latest'
      run: mv target/release/${{ github.event.repository.name }}.exe release/${{ github.event.repository.name }}-windows.exe
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: release-${{ matrix.platform }}
        path: release
