name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3
  
    - name: Create Release Directory
      run: mkdir release

    - name: Build
      run: cargo build --verbose --release --bin rustube-api

    - name: Move Build Output (Ubuntu)
      if: matrix.platform == 'ubuntu-latest'
      run: mv target/release/rustube-api release/rustube-api-ubuntu
      
    - name: Move Build Output (Windows)
      if: matrix.platform == 'windows-latest'
      run: mv target/release/rustube-api.exe release/rustube-api-windows.exe
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: release-${{ matrix.platform }}
        path: release